### ISSUE TITLE
rsyncbackup?

### ISSUE THREAD

**Issue by mick-t** [Lekensteyn/rsyncbackup#1]
Is this the same code or is it based on RSyncBackup by Colin Stewart? See:
- http://www.owlfish.com/software/utils/RSyncBackup/

Thanks!

**Comment by Lekensteyn** [comment]
It is not the same code nor based on Colin's script. Since it uses `rsync` for `backup` purposes and I the script is quite simple, I named it `rsyncbackup`.

No need for a fancy name, this exactly describes what it is used for :smile:

**Comment by mick-t** [comment]
Thanks for the reply! I should have looked at the source and I would have realised that they're different! :)

Thanks!
Mick
